@baseUrl = http://localhost:3000/api/v1

### Sign up
# @name signup
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "firstName": "Tuazon",
  "middleName": "Dolorito",
  "surname": "Kobe Bennedict",
  "studentNumber": "24-1147",
  "course": "BSCS",
  "instiEmail": "tuazon.kobebennedict@collegeofmaryimmaculate.edu.ph",
  "username": "biko",
  "password": "bikolangs5623",
  "confirmPassword": "bikolangs5623"
}

### Sign up 
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "firstName": "Valenzuela",
  "surname": "Anjanette",
  "studentNumber": "24-1148",
  "course": "BSCS",
  "instiEmail": "valenzuela.anjanette@collegeofmaryimmaculate.edu.ph",
  "username": "anj",
  "password": "valenzuela03",
  "confirmPassword": "valenzuela03"
}

### Save these values after signup when your REST client does not support variables
@token = {{signup.response.body.data.token}}
@userId = {{signup.response.body.data.user.id}}

### Log in
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "biko",
  "password": "bikolangs5623"
}

### Log in
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "anj",
  "password": "valenzuela03"
}



