@baseUrl = http://localhost:3000/api/v1

### Sign up
# @name signup
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "firstName": "Tuazon",
  "middleName": "Dolorito",
  "surname": "Kobe Bennedict",
  "studentNumber": "24-1148",
  "course": "BSCS",
  "instiEmail": "tuazon.kobebennedict@collegeofmaryimmaculate.edu.ph",
  "username": "biko",
  "password": "bikolangs5623",
  "confirmPassword": "bikolangs5623"
}

### Save these values after signup when your REST client does not support variables
@token = {{signup.response.body.data.token}}
@userId = {{signup.response.body.data.user.id}}

### Log in
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "biko",
  "password": "bikolangs5623"
}

### Update username and password
PATCH http://localhost:3000/api/v1/users/me
Content-Type: application/json
Authorization: Bearer YOUR_TOKEN_HERE

{
  "username": "newusername",
  "currentPassword": "anjanette03",
  "password": "NewPassword123"
}

### Update username
PATCH http://localhost:3000/api/v1/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMU0xUDdDS0hONURNSlcwTVNIVjZBUTlBMyIsImlhdCI6MTc4ODUyNzgzOSwiZXhwIjoxNzg4NTMxNDM5fQ.pgFWR9z9RLJoAByu_aUDtkkQ9KFC0N-J8mVZIMNNJ3U

{
  "username": "biko"
}
