@baseUrl = http://localhost:3000/api/v1

### Update username and password
PATCH {{baseUrl}}/users/me
Content-Type: application/json
Authorization: Bearer YOUR_TOKEN_HERE

{
  "username": "newusername",
  "currentPassword": "anjanette03",
  "password": "NewPassword123"
}

### Update username
PATCH {{baseUrl}}/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMU0xUDdDS0hONURNSlcwTVNIVjZBUTlBMyIsImlhdCI6MTc4OTAzNzM0OSwiZXhwIjoxNzg5MDQwOTQ5fQ.mchxJL-A3Hrqaq8zSZ7cgKJFczaGMmZR1kVFDSqF5us

{
  "username": "biko"
}


### Delete user soft
DELETE {{baseUrl}}/users/me/soft-delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMU0yN1Y3UzNYSDhQS0tSTkFGSDdXUjVaRiIsImlhdCI6MTc4OTExODIwOSwiZXhwIjoxNzg5MTIxODA5fQ.3U6qXuLxrgyuIws2PNwE5HflfT_I0OIfNVkgxGmuxT0


